#!/usr/bin/ruby

def loud_system(command)
  $stderr.puts command
  system command or raise
end

releaseName = ARGV[0]
releaseTag = releaseName.gsub(/(\d)(\w)/, '\1_\2').gsub('.', '_')

loud_system "git log --pretty --numstat --summary tags/#{releaseTag}.. | scripts/git2cl" 



